title: todo return new
author: hdecarne
#email: hdecarne@gmail.com
description: My tools & knowledge bits, for public use but at your own risk.
remote_theme: hdecarne/hacker

show_excerpts: true
excerpt_separator: "<!--more-->"
