title: todo return new
author: hdecarne
email: hdecarne@gmail.com
description: My tools &amp; knowledge bits

github_username: hdecarne

theme: minima

header_pages:
  - imprint.md

show_excerpts: true
